### ISSUE TITLE
按照运行都没毛病，路径我前面添加了个/，否则的话报无法缩小代码的错误。

### ISSUE THREAD

**Issue by yangge24926** [Beven91/webpack-ant-icon-loader#1]
但是还是将dist.js打包进去了，问题可能出在哪里了，您有建议能告诉一下吗？
我的邮箱：
li_yang18@163.com
万分感谢！

**Comment by Beven91** [comment]
请问是在mac下还是 windows下?，配置能否发下?

**Comment by Beven91** [comment]
不需要在`path.resolve(后添加/` ，压缩错误参见 #2 

目前已修复 ,请重新安装`webpack-ant-icon-loader`到`1.0.5`版本。

**Comment by yangge24926** [comment]
谢谢，我试试，三克油。




Li Yang (李洋) 
Mobile: 18745719420
E-mail: li_yang18@163.com

在2019年03月14日 20:54，beven91 写道：

Closed #1.
