### ISSUE TITLE
Js file is extracted in the incorrect path 

### ISSUE THREAD

**Issue by tylik1** [Beven91/webpack-ant-icon-loader#10]
Hi, I've tried to use the plugin with the existing Laravel project. All js files live in `/public/js` directory, but `0.js` is extracted to `/public` directory. 
Is there any way to tell plugin to write inside `/public/js` directory?

P.S. It is a webpack config

**Comment by Beven91** [comment]
you can set  `webpack.output.chunkFileName`

```js
output: {
    chunkFilename:  'js/[name].js',
  }
```

**Comment by tylik1** [comment]
Thanks a lot @Beven91 

This  config worked for my case.
`
    output: {
            chunkFilename:  'js/[name].js',
            publicPath: '/'
       }
`
