### ISSUE TITLE
你好，这个打包出来的脚本是异步加载的吗

### ISSUE THREAD

**Issue by dongrongcmx** [Beven91/webpack-ant-icon-loader#11]
你好，我打包出来的脚本在html里面是在head标签内部
![image](https://user-images.githubusercontent.com/22345076/56455173-dc5afd80-638d-11e9-80b3-ae14132553c2.png)
请问可以让它异步加载吗

**Comment by Beven91** [comment]
分离出去的icon文件是异步加载的，你的这个文件`chunks/75.e9231fe..` 是怎么拆分出来的？
能贴下`webpack`配置吗？

**Comment by dongrongcmx** [comment]
![image](https://user-images.githubusercontent.com/22345076/56723440-89ad8700-677b-11e9-87e8-cfe45ac8694a.png)
项目是基于next.js的，webpack-ant-icon-loader是按照你的文档来的。其余webpack在next框架内部。如果要改成异步的话，webpack应该在哪儿配置呢

**Comment by Beven91** [comment]
![微信截图_20190425221814](https://user-images.githubusercontent.com/9843457/56743036-6a791e80-67a8-11e9-9065-2d991f32df30.png)

![image](https://user-images.githubusercontent.com/9843457/56743110-8aa8dd80-67a8-11e9-86a6-7935b8958942.png)

我用`nextjs`试了下，是异步加载的。

**Comment by Beven91** [comment]
请问后面怎么说，还是我没有理解你的意思？

**Comment by dongrongcmx** [comment]
不好意思，现在才看到。从加载时间来看确实是在其他静态资源加载完之后才加载的。但是我看到这个js文件加载在head标签里面，并且没有async标识。我以为它不是异步的。

在 2019-04-28 20:21:05，"beven91" <notifications@github.com> 写道：


请问后面怎么说，还是我没有理解你的意思？
