### ISSUE TITLE
你好，我按照你的配置打包后没有任何变化，我使用create-react-app创建的项目最新的版本

### ISSUE THREAD

**Issue by ye-carol** [Beven91/webpack-ant-icon-loader#12]
![image](https://user-images.githubusercontent.com/17829104/56704340-564d0700-673f-11e9-8085-dee79b90f6e2.png)
![image](https://user-images.githubusercontent.com/17829104/56704379-6fee4e80-673f-11e9-9602-e20419fa76ed.png)
![image](https://user-images.githubusercontent.com/17829104/56704399-85637880-673f-11e9-9c03-a5bad02f61a7.png)
想问一下是哪里配置有问题吗？

**Comment by Beven91** [comment]
看配置，貌似没有什么问题，
能把`splitChunks`配置贴给我吗？

**Comment by ye-carol** [comment]
![image](https://user-images.githubusercontent.com/17829104/56778313-49e0b100-6808-11e9-8728-e1de3be4494a.png)

**Comment by ye-carol** [comment]
![image](https://user-images.githubusercontent.com/17829104/56779181-4fd89100-680c-11e9-8614-9fd723df650a.png)

**Comment by H-Sven** [comment]
cnpm i 安装的插件，执行npm run build 后没有生效
改为npm后正常

猜测原因是  cnpm安装的 antd 和 npm安装的antd 包名称不一样

 `path.resolve('node_modules/@ant-design/icons/lib/dist')` 无法匹配到cnpm 安装的antd

希望能够兼容一下cnpm的包

**Comment by ye-carol** [comment]
我一直都是npm安装的从来没用过cnpm的

![image](https://user-images.githubusercontent.com/17829104/58307660-f4f98000-7e31-11e9-8ae5-09bfdb84151f.png)

**Comment by Beven91** [comment]
如果您的项目中使用了`optimization.splitChunks` ，且设置了`chunks:'all'`

请注意，需要将字体图标的`chunk`排除下，例如:

```js
module.exports = {
   optimization: {
    splitChunks: {
      cacheGroups: {
        // chunks:'all',
        chunks:function(chunk){
            // 这里的name 可以参考在使用`webpack-ant-icon-loader`时指定的`chunkName`
            return chunk.name !== 'antd-icons'; 
        },
        vendors: {
          filename: '[name].bundle.js'
        }
      }
    }
  }
}
```
