### ISSUE TITLE
【问题反馈】 使用cnpm安装的包打包无效

### ISSUE THREAD

**Issue by H-Sven** [Beven91/webpack-ant-icon-loader#13]
cnpm i 安装的插件，执行npm run build 后没有生效
改为npm后正常

猜测原因是  cnpm安装的 antd 和 npm安装的antd 包名称不一样

 `path.resolve('node_modules/@ant-design/icons/lib/dist')` 无法匹配到cnpm 安装的antd

希望能够兼容一下cnpm的包

**但是发现，是将原来的600多kb的文件 分成了一个200kb 和 一个400kb的包，我在页面加载的时候这个400kb的文件依然会加载，但是我并没有引入Icon组件，请问这是正常的吗**

**Comment by Beven91** [comment]
是的，分离出去的包，是作为异步加载，主要目前是提升`主js`的加载速度。

**Comment by Beven91** [comment]
关于
```
 path.resolve('node_modules/@ant-design/icons/lib/dist`)`
```
无法匹配的问题，你可以改成如下试试:

```
require.resolve('@ant-design/icons/lib/dist')
```

试试。
