### ISSUE TITLE
Chunk Name

### ISSUE THREAD

**Issue by ghost** [Beven91/webpack-ant-icon-loader#14]
How can define the filename for the chunk ?

I have this in webpack:
      chunkFilename: "static/js/[name].chunk.js"

but, Can I set the name through this loader ?

**Comment by Beven91** [comment]
- upgrade `webpack-ant-icon-loader` to `1.0.8` 

- add config `loader.options.chunkName` 

```js
module.exports = {
  module:{
    rules:[
      {
        loader:'webpack-ant-icon-loader',
        enforce: 'pre',
        options:{
           chunkName:'antd-icons', // default is antd-icons
        },
        include:[
          require.resolve('@ant-design/icons/lib/dist')
        ]
      }
    ]
  }
}

```

**Comment by ghost** [comment]
@Beven91 excellent! thank you! 👍
