### ISSUE TITLE
分包延迟之后，动态加载的路径不对

### ISSUE THREAD

**Issue by light212** [Beven91/webpack-ant-icon-loader#17]
publicPath:'./',
chunkFilename:'[name]/[name].plugins.js'
这么去配置，动态加载的时候是从项目根去访问，而不是从我配置的目录根去访问的。

**Comment by Beven91** [comment]
两个访问`url`发我下

**Comment by light212** [comment]
![image](https://user-images.githubusercontent.com/12542944/59749675-13775d80-92b0-11e9-9dc9-c9c400174bc6.png)

**Comment by Beven91** [comment]
你的`publicPath` 设置了 `./` 应该就没有问题的,这部分是`webpack`官方的拆分引用方案。

**Comment by light212** [comment]
文件生成的目录都对着，但是动态去加载的路径不对。

**Comment by Beven91** [comment]
正确的url应该是哪个?

**Comment by light212** [comment]
http://cis.test/conversation/tnttalk/

**Comment by light212** [comment]
上面是正确url

**Comment by Beven91** [comment]
`build.js`的url是？
能把你的`index.html`内容贴下吗？

**Comment by light212** [comment]
{
entry: {
        // admin: './admin/src/app.js'
        // travel: './travel/src/app.js',
        // history: './history/src/app.js'
        // h5: './h5/src/app.js',
        tnttalk: ['babel-polyfill','./tnttalk/src/app.js']
        // vendors: ['react','jquery','antd']
    },
    // watch:true,
    resolve: {
        // modulesDirectories: ['node_modules', join(__dirname, '../node_modules')],
        extensions: ['.ts', '.tsx', '.js', '.jsx', '.json'],
        alias: {
            '@adminUtils': path.join(rootPath, 'admin/src/utils'),
            '@adminImages': path.join(rootPath, 'admin/images')
        }
    },
    output: {
        publicPath:'./',
        filename: '[name]/build.js',
        path: path.resolve(__dirname, './'),
        chunkFilename: 'vendors.plugins.js'
    }
}
build.js 是引入到页面的js，分包的vendors.plugins.js 这个是用的这个插件分包出来的。

**Comment by light212** [comment]
http://cis.test/conversation/tnttalk/build.js
这就是完整的url
动态加载的那个生成的路径也是在tnttalk/下面。
页面访问的时候生成的路径指向不对。

**Comment by Beven91** [comment]
·`html`的`script`引用能发我下吗？

**Comment by light212** [comment]
document.write(unescape('%3Cscript src="/conversation/tnttalk/build.js?v=2" type="text/javascript" %3E%3C/script%3E'));

**Comment by Beven91** [comment]
你可以把 `publicPath` 配置成  '/conversation/tnttalk/'  
因为如果这里使用`publicPath: './'`的话，那么会跟随当前页面的`path`有关系，所以这里推荐你配置下

```
module.exports = {
  output:{
     publicPath:isProduction ? '/conversation/tnttalk/':'./'
  }
}

```

**Comment by light212** [comment]
嗯，确实跟publicPath有关，感谢！
