### ISSUE TITLE
使用 umi 时的配置

### ISSUE THREAD

**Issue by shiny** [Beven91/webpack-ant-icon-loader#3]
建议文档增加 umi 配置的说明，因为它是 ant.d 文档中默认使用的技术栈，而版本 2 开始不支持 `webpack.config.js`，而采用 chainWebpack

**Comment by Beven91** [comment]
谢谢提醒，已添加到`README.md`

**Comment by shiny** [comment]
感谢，因为在 ant.design 的官网文档看到了此项目 https://github.com/ant-design/ant-design/pull/15402/files
