### ISSUE TITLE
你好，那个我按照你的方法。但是没有效果

### ISSUE THREAD

**Issue by Beven91** [Beven91/webpack-ant-icon-loader#6]
你好，那个我按照你的方法。但是没有效果

_Originally posted by @xiaobinwu in https://github.com/Beven91/webpack-ant-icon-loader/issues/5#issuecomment-475173758_

**Comment by Beven91** [comment]
能贴下你的`webpack`配置嘛

**Comment by xiaobinwu** [comment]
https://github.com/Beven91/webpack-ant-icon-loader/issues/5#issuecomment-475462231

**Comment by xiaobinwu** [comment]
得到的图标svg没有内容
![image](https://user-images.githubusercontent.com/9909704/54797871-ec999300-4c90-11e9-864d-c27ff357183c.png)

**Comment by xiaobinwu** [comment]
感觉是` // 通过强制刷新来，显示异步加载的图标    
    this.instances.forEach((instance) => instance.forceUpdate());`这里没有强制刷新成功

**Comment by Beven91** [comment]
使用的antd版本是多少？

**Comment by Beven91** [comment]
或者方便提供能访问的链接吗？我可以分析看看。

**Comment by xiaobinwu** [comment]
最新版本呢

**Comment by Beven91** [comment]
嗨，问题解决了吗？ 我尝试了几次，分别使用 mac和windows下，没有重现到。
